name: riverpod_clean_architecture_lib
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^5.0.3
  webview_flutter: ^4.4.1
  convex_bottom_bar: ^3.2.0
  jiffy: ^6.2.1
  shared_preferences: ^2.0.10
  logger: ^1.1.0
  pretty_dio_logger: ^1.1.1
  fluttertoast: ^8.0.8
  image_picker: ^1.0.0
  uuid: ^3.0.6
  intl: ^0.18.0
  cached_network_image: ^3.3.0
  url_launcher: ^6.0.4
  dartz: ^0.10.1
  flutter_image_compress: ^2.1.0
  riverpod: ^2.5.0
  flutter_riverpod: ^2.4.0
  firebase_core: ^2.16.0
  firebase_crashlytics: ^3.3.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0



flutter:

