name: riverpod_clean_architecture_lib
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  args: ^2.0.0
  cupertino_icons: ^1.0.2
  dio: ^5.0.3
  jiffy: ^6.2.1
  shared_preferences: ^2.0.10
  logger: ^1.1.0
  pretty_dio_logger: ^1.1.1
  uuid: ^3.0.6
  intl: ^0.19.0
  dartz: ^0.10.1
  riverpod: ^2.5.1
  sqflite: ^2.0.0
  flutter_riverpod: ^2.4.0
  firebase_core: ^3.6.0
  firebase_crashlytics: ^4.1.3
  cloud_firestore: ^5.4.3
  firebase_storage: ^12.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

executables:
  my_flutter_tool: bin/rc_cli


flutter:

