name: riverpod_clean_architecture_lib
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  args: ^2.6.0
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  jiffy: ^6.3.1
  shared_preferences: ^2.3.2
  logger: ^2.4.0
  pretty_dio_logger: ^1.4.0
  fluttertoast: ^8.2.8
  uuid: ^4.5.1
  intl: ^0.19.0
  url_launcher: ^6.3.1
  dartz: ^0.10.1
  riverpod: ^2.6.1
  sqflite: ^2.4.0
  flutter_riverpod: ^2.6.1
  firebase_core: ^3.6.0
  firebase_crashlytics: ^4.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

executables:
  my_flutter_tool: bin/rc_cli


flutter:

