name: riverpod_clean_architecture_lib
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  args: ^2.0.0
  cupertino_icons: ^1.0.2
  dio: ^5.0.3
  jiffy: ^6.2.1
  shared_preferences: ^2.0.10
  logger: ^1.1.0
  pretty_dio_logger: ^1.1.1
  fluttertoast: ^8.0.8
  uuid: ^3.0.6
  intl: ^0.18.0
  url_launcher: ^6.0.4
  dartz: ^0.10.1
  riverpod: ^2.5.0
  sqflite: ^2.0.0
  flutter_riverpod: ^2.4.0
  firebase_core: ^2.16.0
  firebase_crashlytics: ^3.3.6
  cloud_firestore: ^4.9.2
  firebase_storage: ^11.2.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

executables:
  my_flutter_tool: bin/rc_cli


flutter:

